### ISSUE TITLE
`.post()` for form elements does not set the standard Content type of 'application/x-www-form-urlencoded'

### ISSUE THREAD

**Issue by jwestbrook** [Twipped/wellrested#39]

**Comment by Twipped** [comment]
This was an issue with Superagent 6.0. Wellrested 4.0 now requires Superagent 7, which now defaults to sending the `application/json` content type, as that is how it defaults to sending post data. If you want to send form data by default you can set `headers: { 'Content-Type': 'application/x-www-form-urlencoded' }` in the wellrested config and SuperAgent will automatically switch over, or you can call `.type('form')` on the individual request.
